[package]
name = "murtlatif/spring"
description = "Spring module forked from Quenty/NevermoreEngine, slightly modified to include types."
version = "0.1.2"
license = "MIT"
authors = ["Quenty", "Defaultio", "Murt"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]