[package]
name = "rakha/actually-good-td"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Matter = "evaera/matter@0.7.0"
Fusion = "elttob/fusion@0.2.0"
ParallelWorker = "maximumadhd/parallel-worker@1.0.0"
TableUtil = "sleitnick/table-util@1.2.1"
Loader = "sleitnick/loader@2.0.0"
Spring = "murtlatif/spring@0.1.2"
PartCache = "aulkhami/partcache@4.0.2"
