[package]
name = "rakha/actually-good-td"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Matter = "evaera/matter@0.7.0"
Fusion = "elttob/fusion@0.2.0"
Reflex = "littensy/reflex@4.3.1"
ParallelWorker = "maximumadhd/parallel-worker@1.0.0"
Sift = "csqrl/sift@0.0.8"
Immut = "solarhorizon/immut@0.4.4"
Loader = "sleitnick/loader@2.0.0"
Spring = "murtlatif/spring@0.1.2"
PartCache = "aulkhami/partcache@4.0.2"
Plasma = "matter-ecs/plasma@0.4.4"
Rewire = "sayhisam1/rewire@0.3.0"
