local assets = {
	StatIcons = {
		Attack = "rbxassetid://18159822676",
		AttackInterval = "rbxassetid://18159822939",
		Defense = "rbxassetid://18159822402",
		Health = "rbxassetid://18159822100",
		Range = "rbxassetid://18373425065",
	},
	MiscGui = {
		RightTriangleBL = "rbxassetid://18240161401",
		XCross = "rbxassetid://18240534736",
	},
	SurfaceGui = {
		RangeVisual = "rbxassetid://18377799527",
		Highlight = "rbxassetid://18377940898",
	},
}

return assets
